/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.EclectricityUtility;

import UserInterface.UtilityCompanies.UtilityContractForm;
import UserInterface.UtilityCompanies.UtilityCompFormDetails;
import UserInterface.ManagementCompany.MgtCompFormDetails;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ankitlall
 */
public class ElectricityContractFormCont extends javax.swing.JPanel {
    
    int appId;
    
    /**
     * Creates new form ElectricityContractForm
     */
    public ElectricityContractFormCont(int appId) {
        this.appId=appId;
        initComponents();
        populateCombobox();
        contentPanel.add(new UtilityContractForm(appId, "electricity"));
    }
    
        private void populateCombobox() {
        DefaultComboBoxModel<String> cmbModel = new DefaultComboBoxModel<>(getDropdownValues());
        formType.setModel(cmbModel);
        formType.setSelectedItem("Gas Company Form");
    }
    
    private String[] getDropdownValues() {
        return new String[] {"Management Company Form", "Electricity Company Form"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        formType = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(810, 700));
        setSize(new java.awt.Dimension(810, 700));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contract Form Details");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        formType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        formType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addComponent(formType, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(621, 621, 621))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(formType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTypeActionPerformed
        // TODO add your handling code here:
        String selected = String.valueOf(formType.getSelectedItem());

        contentPanel.removeAll();

        switch(selected) {
            case "Management Company Form":
            contentPanel.add(new MgtCompFormDetails(appId));
            break;
            case "Electricity Company Form":
            contentPanel.add(new UtilityCompFormDetails(appId, "electricity"));
            break;
        }

        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_formTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JComboBox<String> formType;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
